# Generated by Django 3.2.14 on 2022-11-17 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20221117_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourites',
            options={'default_related_name': 'favourites', 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'default_related_name': 'shopping_list', 'verbose_name': 'Список покупок', 'verbose_name_plural': 'Списки покупок'},
        ),
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='unique_unit_measurement_of_ingredients',
        ),
    ]
