# Generated by Django 3.2.14 on 2022-11-17 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20221117_2122'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredientinrecipe',
            name='unique_recipe_ingredient',
        ),
    ]
