# Generated by Django 3.2.14 on 2022-11-17 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_recipe_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cart',
        ),
    ]
